### ISSUE TITLE
モデル学習のコードを公開していただいてもよろしいでしょうか

### ISSUE THREAD

**Issue by neilctwu** [tanreinama/gpt2-japanese#2]
初めまして、WUと申します。
日本語のGPT-2を使った文章生成モデルを公開していただきありがとうございます。
他のデータを使ってモデルを作ってみたいと思っていますが、学習部分のコードを公開していただいてもよろしいでしょうか？
よろしくお願いします。

**Comment by tanreinama** [comment]
学習コードはGPT2のオフィシャルにあるコードそのままですよ。頑張ってください。
