### ISSUE TITLE
pytorch transformers対応

### ISSUE THREAD

**Issue by ycat3** [tanreinama/gpt2-japanese#3]
素晴らしいプロジェクトなので利用したいのですが、Ubuntu20.04.1の環境では
tensorflow-gpu==1.15.2の動作環境が構築困難なので、現在利用できません。
pytorch transformersに対応してくれればもっと利用しやすくなると思いますが。

**Comment by tanreinama** [comment]
中国語のページですが以下の手順でインストール出来るはずですが。
https://www.jianshu.com/p/5ce10c7600c8

**Comment by ycat3** [comment]
早速のご連絡有難うございます。
Ubuntu 18.04の環境でインストールして、実行できました。
京都大学のBERT日本語Pretrainedモデル等のようにTF用だけではなくPytorch用のGPT2日本語モデルは公開する予定はありますか。

**Comment by tanreinama** [comment]
余裕があったら作りたいですが、向こう数ヶ月は機械学習用マシンの予定が埋まっているので不可能な状態です。
プログラミングの進捗より、単純に利用出来るマシンの有無が制限となっている現状です。
