### ISSUE TITLE
out['h_flat'] の 値が [] 

### ISSUE THREAD

**Issue by takky0330** [tanreinama/gpt2-japanese#5]
素晴らしいプロジェクトで感謝しております。
Small（117M）のモデルも利用させていただいております。ありがとうございます。

※ クラウドファンディングでの支援の予定は把握しておりましたが…
　この更新を把握した時点で、クラウドファンディングは終了しており、支援をさせていただくことができませんでした…
　なにか別の形で（大した額ではありませんが）支援させていただく方法はありませんか？？

現在、Mediumも公開いただいたため、こちらに置き換えております。

Smallの時点では発生していなかったのですが、Mediumのモデルとコードをベースにベクトルを取得しようとすると
いくつかの文で、out['h_flat'] の 値が [] で返ってきているようで…   以下の部分で、エラーになってしまいます。
     vector.append(out['h_flat'][-1])

out['h_flat'] はどのような場合に [] で返す可能性があるのかお分かりでしょうか？？

自分でもこれから調べようと思っておりますが… もし把握されていたりしたら、ご教示いただけますと幸いです。
よろしくお願いいたします。

**Comment by tanreinama** [comment]
```python
vector.append(out['h_flat'][-1])
```

このコードは古いソースコードの方に新しいモデルを組み合わせてませんか？
最新のソースコードの方をpullし直して試してみてください。

**Comment by takky0330** [comment]
ご回答ありがとうございます。
pullし直しつつコードをもう一度整理して、テストし直してみます。

ありがとうございました！

**Comment by takky0330** [comment]
再度、すみません…
クリアな状態の gpt2-transform.py で試しました。

```
$ python3 gpt2-transform.py --context="ない"
2020-11-24 19:48:36.668995: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Traceback (most recent call last):
  File "gpt2-transform.py", line 69, in <module>
    output = out['h_flat'][-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

Small／Medium でも比較しました。
［Medium］
　　 --context="ない"　：　エラー
　　 --context="無い"　：　エラーにならない
［Small］
　　 --context="ない"　：　エラーにならない
　　 --context="無い"　：　エラーにならない

私の環境の問題でしょうか？？

**Comment by takky0330** [comment]
傾向としては…
`enc.encode(context)` の結果が、1次元の場合に、`out['h_flat']` の値が [] になりますね。

＂なし＂、＂はし＂、＂橋＂、＂今日＂、＂挨拶＂ などなど…  （全てSmallではエラーにはなりません）
はて…  これはどう取り扱いましょうかね？？

**Comment by tanreinama** [comment]
リオープンします

**Comment by tanreinama** [comment]
generateの方だけ直してtransformの方に修正残が残っていました。修正してPushしたので、最新のソースコードの方でお願いします。

**Comment by takky0330** [comment]
ありがとうございます！！
助かりましたァ…
後ほど、ソースを更新してトライしてみます！！

**Comment by takky0330** [comment]
確認が取れました。
修正箇所も確認し、こちらのコードにも反映させていただき、解消したことを確認しました。
すばやいご対応、ありがとうございました！！
