### ISSUE TITLE
mediumモデルのレイヤー数、総パラメーター数

### ISSUE THREAD

**Issue by rsimmons** [tanreinama/gpt2-japanese#6]
拙い日本語ですみません。
`report/models.md`では:

総パラメーター数: **274041856**
レイヤー数: 16 heads, **20** layers

と書いてありますが、自分の計算では:

総パラメーター数: **324426752**
レイヤー数: 16 heads, **24** layers

の方がが正しいではないかと思っております。

`print(sum(np.prod(v.get_shape()) for v in tf.trainable_variables()))`
-> 324426752

`gpt2ja-medium/model-10410000.data-00000-of-00001` is 1297707008 bytes = 4* 324426752

original gpt-2 medium (355M) vocabulary: 50257
gpt2ja-medium vocabulary: 20573
`n_embd` (both): 1024
324426752 + (50257-20573)*1024 = 354823168 (~355M)

よろしくお願いいたします。

**Comment by tanreinama** [comment]
指摘してくれてありがとうございます。
ご指摘の通り、24レイヤーが正しいです。
単純にtypoと以前のモデルのパラメーター数と混ざったです。
