### ISSUE TITLE
[提案]転移学習への対応

### ISSUE THREAD

**Issue by kzaukzau** [tanreinama/gpt2-japanese#7]
素晴らしいプロジェクトなので利用したいのですが、

１
転移学習が簡単に行なえません。

　gpt-2-simple
　https://github.com/minimaxir/gpt-2-simple
　のようにできれば、使えば大変助かります。

２
始まりの文章と終わりの文章を同時に指定することは可能でしょうか？

**Comment by tanreinama** [comment]
1.
転移学習のコードは手元にあるのですが、これは、学習のためのサーバー代をクラウドファウンディングで集めたときのリターンにしてしまったので、しばらくの間は支援者の方だけに共有しています。プロジェクトが完遂されたタイミングで公開したいと思ってはいます。

2.
GPT-2では終わりを指定することは出来ません。
BERTのモデルなら、真ん中だけ[MASK]にして穴埋め問題を解かせれば、始まりと終わりを指定出来ますが、生成する部分の単語数が固定になります。上手く組み合わせて使ってみてください。
ちなみにBERTモデルも公開しています（こちらには転移学習のコードもあります）。
https://github.com/tanreinama/RoBERTa-japanese

**Comment by kzaukzau** [comment]
ご返信を頂きありがとうございます。

1　より素晴らしいモデルと転移学習コードを待ちます。

2　BERTの転移学習コードの公開ありがとうございます。
